import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import {
  Outlet,
  Link,
  createRootRouteWithContext,
  useRouter,
  HeadContent,
  Scripts,
} from "@tanstack/react-router";
import { Suspense, lazy, useEffect, type ReactNode } from "react";

import appCss from "../styles.css?url";
import { reportLovableError } from "../lib/lovable-error-reporting";
import { Toaster } from "../components/ui/sonner";
import AnnouncementBar from "../components/layout/AnnouncementBar";
import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";
import { Announcer } from "../components/a11y/Announcer";
import { useAccountSync } from "@/hooks/useAccountSync";
import { useSearchHotkey } from "../hooks/useSearchHotkey";
import { useOverlay } from "../store/ui-store";
import { OG_IMAGE, organizationAndWebsiteJsonLd } from "@/lib/site-jsonld";

// Phase 6 requires these two to be dynamically imported: neither is on screen
// at first paint, and together they pull in the cart, the search panel and
// their toasts. They load the first time an overlay is opened.
const CartDrawer = lazy(() => import("../components/cart/CartDrawer"));
const SearchModal = lazy(() => import("../components/search/SearchModal"));

function NotFoundComponent() {
  return (
    <div className="flex min-h-screen items-center justify-center bg-background px-4">
      <div className="max-w-md text-center">
        <h1 className="text-7xl font-bold text-foreground">404</h1>
        <h2 className="mt-4 text-xl font-semibold text-foreground">Page not found</h2>
        <p className="mt-2 text-sm text-muted-foreground">
          The page you're looking for doesn't exist or has been moved.
        </p>
        <div className="mt-6">
          <Link
            to="/"
            className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90"
          >
            Go home
          </Link>
        </div>
      </div>
    </div>
  );
}

function ErrorComponent({ error, reset }: { error: Error; reset: () => void }) {
  console.error(error);
  const router = useRouter();
  useEffect(() => {
    reportLovableError(error, { boundary: "tanstack_root_error_component" });
  }, [error]);

  return (
    <div className="flex min-h-screen items-center justify-center bg-background px-4">
      <div className="max-w-md text-center">
        <h1 className="text-xl font-semibold tracking-tight text-foreground">
          This page didn't load
        </h1>
        <p className="mt-2 text-sm text-muted-foreground">
          Something went wrong on our end. You can try refreshing or head back home.
        </p>
        <div className="mt-6 flex flex-wrap justify-center gap-2">
          <button
            onClick={() => {
              router.invalidate();
              reset();
            }}
            className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90"
          >
            Try again
          </button>
          <a
            href="/"
            className="inline-flex items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium text-foreground transition-colors hover:bg-accent"
          >
            Go home
          </a>
        </div>
      </div>
    </div>
  );
}

export const Route = createRootRouteWithContext<{ queryClient: QueryClient }>()({
  head: () => ({
    meta: [
      { charSet: "utf-8" },
      { name: "viewport", content: "width=device-width, initial-scale=1" },
      { title: "Khawaja Collection — Premium Pakistani Fashion" },
      {
        name: "description",
        content:
          "Khawaja Collection: premium Pakistani fashion for women and men, made in limited runs in Lahore.",
      },
      { property: "og:site_name", content: "Khawaja Collection" },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
      // A site-wide default so a route that forgets Open Graph still shares
      // as a card rather than a bare link. Every route that matters overrides
      // it through seoHead().
      { property: "og:image", content: OG_IMAGE.path },
      { property: "og:image:width", content: String(OG_IMAGE.width) },
      { property: "og:image:height", content: String(OG_IMAGE.height) },
      { property: "og:image:alt", content: OG_IMAGE.alt },
    ],
    links: [
      { rel: "stylesheet", href: appCss },
      // Section 14: fonts are self-hosted and latin-subset (public/fonts,
      // generated by scripts/fetch-fonts.mjs). The Google CDN cost four round
      // trips before text could paint in the right face — resolve
      // googleapis, fetch CSS, discover gstatic, resolve that, then the font.
      //
      // Only the two faces used above the fold are preloaded: the display
      // serif for the h1 and the body grotesque. Preloading all six would
      // compete with the LCP image for bandwidth to fetch weights most pages
      // never use. The rest load normally when something asks for them.
      {
        rel: "preload",
        href: "/fonts/cormorant-garamond-500.woff2",
        as: "font",
        type: "font/woff2",
        crossOrigin: "anonymous",
      },
      {
        rel: "preload",
        href: "/fonts/inter-400.woff2",
        as: "font",
        type: "font/woff2",
        crossOrigin: "anonymous",
      },
      { rel: "icon", href: "/favicon.ico", type: "image/x-icon" },
    ],
    scripts: [
      {
        type: "application/ld+json",
        children: JSON.stringify(organizationAndWebsiteJsonLd()),
      },
    ],
  }),
  shellComponent: RootShell,
  component: RootComponent,
  notFoundComponent: NotFoundComponent,
  errorComponent: ErrorComponent,
});

function RootShell({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        <HeadContent />
      </head>
      <body>
        {children}
        <Scripts />
      </body>
    </html>
  );
}

function RootComponent() {
  const { queryClient } = Route.useRouteContext();
  const overlay = useOverlay();
  useSearchHotkey();
  useAccountSync();

  return (
    <QueryClientProvider client={queryClient}>
      <AnnouncementBar />
      <Header />
      <main>
        {/* Required: nested routes render here. Removing <Outlet /> breaks all child routes. */}
        <Outlet />
      </main>
      <Footer />

      {/* Mounted only while open, so the chunk is never fetched for a visitor
          who does not touch the bag or the search field. */}
      <Suspense fallback={null}>
        {overlay === "cart" ? <CartDrawer /> : null}
        {overlay === "search" ? <SearchModal /> : null}
      </Suspense>

      <Announcer />
      <Toaster position="bottom-right" />
    </QueryClientProvider>
  );
}
