/**
 * Downloads the two brand faces and writes a local @font-face stylesheet.
 * docs/BUILD-SPEC.pdf Section 6.2 and Section 14:
 *
 *   "Fonts: 2 families, subset to latin, display: swap, self-hosted"
 *
 *   node scripts/fetch-fonts.mjs
 *
 * WHY SELF-HOST. On the Google CDN the browser has to resolve
 * fonts.googleapis.com, fetch a stylesheet, discover fonts.gstatic.com, resolve
 * that too, and only then start the font — four round trips before any text can
 * paint in the right face. On 4G that is most of the LCP budget. Self-hosted,
 * the font is on the same origin as the HTML that references it and starts
 * immediately.
 *
 * WHY ONLY THE LATIN SUBSET. Google serves each family split by unicode range.
 * The full set for Cormorant Garamond includes Cyrillic and Vietnamese, which
 * this shop will never render. Taking only the `latin` block is the difference
 * between roughly 20 KB and roughly 120 KB per weight.
 *
 * ON THE USER AGENT. Requesting the stylesheet without a modern browser UA gets
 * you TTF, which is several times the size of woff2 and has no subsetting. The
 * UA below is what makes Google return the woff2 + unicode-range version.
 *
 * The downloaded files are committed. Re-run this only to change weights or
 * families; a version bump on Google's side would otherwise silently change
 * what the site ships.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const FONT_DIR = join(ROOT, "public", "fonts");
const CSS_FILE = join(ROOT, "src", "fonts.css");

// Chrome on Windows. See the note above — this is what selects woff2.
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36";

/** Section 6.2 — a display serif and a neutral grotesque, three weights each. */
const FAMILIES = [
  {
    name: "Cormorant Garamond",
    css: "Cormorant+Garamond",
    weights: [400, 500, 600],
    slug: "cormorant-garamond",
  },
  { name: "Inter", css: "Inter", weights: [400, 500, 600], slug: "inter" },
];

/** The `latin` block, identified by the basic-latin range every one of them carries. */
function isLatinSubset(unicodeRange) {
  return unicodeRange.includes("U+0000-00FF");
}

function parseFaces(css) {
  const faces = [];
  const blockRe = /@font-face\s*\{([^}]*)\}/g;
  let match;
  while ((match = blockRe.exec(css)) !== null) {
    const block = match[1];
    const pick = (prop) => (block.match(new RegExp(`${prop}:\\s*([^;]+);`)) ?? [])[1]?.trim();
    const url = (block.match(/url\((https:[^)]+)\)/) ?? [])[1];
    if (!url) continue;
    faces.push({
      weight: pick("font-weight"),
      style: pick("font-style"),
      unicodeRange: pick("unicode-range") ?? "",
      url,
    });
  }
  return faces;
}

mkdirSync(FONT_DIR, { recursive: true });

const cssParts = [
  "/*",
  " * Self-hosted brand faces. GENERATED by scripts/fetch-fonts.mjs — do not edit.",
  " * docs/BUILD-SPEC.pdf Sections 6.2 and 14: two families, latin subset only,",
  " * display: swap, served from our own origin.",
  " *",
  " * Cormorant Garamond and Inter are both SIL Open Font License 1.1.",
  " */",
  "",
];

let total = 0;

for (const family of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?family=${family.css}:wght@${family.weights.join(";")}&display=swap`;
  const css = await fetch(url, { headers: { "User-Agent": UA } }).then((r) => {
    if (!r.ok) throw new Error(`${family.name}: stylesheet request failed (${r.status})`);
    return r.text();
  });

  const latin = parseFaces(css).filter((face) => isLatinSubset(face.unicodeRange));
  if (latin.length !== family.weights.length) {
    throw new Error(
      `${family.name}: expected ${family.weights.length} latin faces, found ${latin.length}. ` +
        `Google may have changed its subsetting — check before committing.`,
    );
  }

  for (const face of latin) {
    const file = `${family.slug}-${face.weight}.woff2`;
    const bytes = Buffer.from(await fetch(face.url).then((r) => r.arrayBuffer()));
    writeFileSync(join(FONT_DIR, file), bytes);
    total += bytes.length;
    console.log(`  ${file.padEnd(32)} ${(bytes.length / 1024).toFixed(1)} KB`);

    cssParts.push(
      "@font-face {",
      `  font-family: "${family.name}";`,
      `  font-style: ${face.style};`,
      `  font-weight: ${face.weight};`,
      "  font-display: swap;",
      `  src: url("/fonts/${file}") format("woff2");`,
      `  unicode-range: ${face.unicodeRange};`,
      "}",
      "",
    );
  }
}

writeFileSync(CSS_FILE, cssParts.join("\n"));
console.log(
  `\n${(total / 1024).toFixed(1)} KB of fonts -> public/fonts, stylesheet -> src/fonts.css`,
);
