/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as BridalRouteImport } from './routes/bridal'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewArrivalsRouteImport } from './routes/new-arrivals'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReadyToWearRouteImport } from './routes/ready-to-wear'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SaleRouteImport } from './routes/sale'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as UnstitchedRouteImport } from './routes/unstitched'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as AccessoriesIndexRouteImport } from './routes/accessories/index'
import { Route as AccessoriesSubcategoryRouteImport } from './routes/accessories/$subcategory'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountAddressesRouteImport } from './routes/account/addresses'
import { Route as ApiNewsletterRouteImport } from './routes/api/newsletter'
import { Route as ApiOrdersRouteImport } from './routes/api/orders'
import { Route as ApiProductRouteImport } from './routes/api/product'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiTrackOrderRouteImport } from './routes/api/track-order'
import { Route as ApiWishlistEntriesRouteImport } from './routes/api/wishlist-entries'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as CollectionsSlugRouteImport } from './routes/collections/$slug'
import { Route as MenIndexRouteImport } from './routes/men/index'
import { Route as MenSubcategoryRouteImport } from './routes/men/$subcategory'
import { Route as OrdersOrderNumberRouteImport } from './routes/orders/$orderNumber'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as ProductsSlugRouteImport } from './routes/products/$slug'
import { Route as WomenIndexRouteImport } from './routes/women/index'
import { Route as WomenSubcategoryRouteImport } from './routes/women/$subcategory'
import { Route as AccountOrdersIndexRouteImport } from './routes/account/orders.index'
import { Route as AccountOrdersOrderNumberRouteImport } from './routes/account/orders.$orderNumber'
import { Route as ApiAccountOrdersRouteImport } from './routes/api/account/orders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BridalRoute = BridalRouteImport.update({
  id: '/bridal',
  path: '/bridal',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewArrivalsRoute = NewArrivalsRouteImport.update({
  id: '/new-arrivals',
  path: '/new-arrivals',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadyToWearRoute = ReadyToWearRouteImport.update({
  id: '/ready-to-wear',
  path: '/ready-to-wear',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleRoute = SaleRouteImport.update({
  id: '/sale',
  path: '/sale',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const UnstitchedRoute = UnstitchedRouteImport.update({
  id: '/unstitched',
  path: '/unstitched',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesIndexRoute = AccessoriesIndexRouteImport.update({
  id: '/accessories/',
  path: '/accessories/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesSubcategoryRoute = AccessoriesSubcategoryRouteImport.update({
  id: '/accessories/$subcategory',
  path: '/accessories/$subcategory',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AccountRoute,
} as any)
const ApiNewsletterRoute = ApiNewsletterRouteImport.update({
  id: '/api/newsletter',
  path: '/api/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersRoute = ApiOrdersRouteImport.update({
  id: '/api/orders',
  path: '/api/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductRoute = ApiProductRouteImport.update({
  id: '/api/product',
  path: '/api/product',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackOrderRoute = ApiTrackOrderRouteImport.update({
  id: '/api/track-order',
  path: '/api/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWishlistEntriesRoute = ApiWishlistEntriesRouteImport.update({
  id: '/api/wishlist-entries',
  path: '/api/wishlist-entries',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MenIndexRoute = MenIndexRouteImport.update({
  id: '/men/',
  path: '/men/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenSubcategoryRoute = MenSubcategoryRouteImport.update({
  id: '/men/$subcategory',
  path: '/men/$subcategory',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderNumberRoute = OrdersOrderNumberRouteImport.update({
  id: '/orders/$orderNumber',
  path: '/orders/$orderNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WomenIndexRoute = WomenIndexRouteImport.update({
  id: '/women/',
  path: '/women/',
  getParentRoute: () => rootRouteImport,
} as any)
const WomenSubcategoryRoute = WomenSubcategoryRouteImport.update({
  id: '/women/$subcategory',
  path: '/women/$subcategory',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersIndexRoute = AccountOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersOrderNumberRoute =
  AccountOrdersOrderNumberRouteImport.update({
    id: '/orders/$orderNumber',
    path: '/orders/$orderNumber',
    getParentRoute: () => AccountRoute,
  } as any)
const ApiAccountOrdersRoute = ApiAccountOrdersRouteImport.update({
  id: '/api/account/orders',
  path: '/api/account/orders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/bridal': typeof BridalRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/privacy': typeof PrivacyRoute
  '/ready-to-wear': typeof ReadyToWearRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/returns': typeof ReturnsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sale': typeof SaleRoute
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/unstitched': typeof UnstitchedRoute
  '/wishlist': typeof WishlistRoute
  '/accessories/$subcategory': typeof AccessoriesSubcategoryRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/api/newsletter': typeof ApiNewsletterRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/product': typeof ApiProductRoute
  '/api/search': typeof ApiSearchRoute
  '/api/track-order': typeof ApiTrackOrderRoute
  '/api/wishlist-entries': typeof ApiWishlistEntriesRoute
  '/category/$slug': typeof CategorySlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/men/$subcategory': typeof MenSubcategoryRoute
  '/orders/$orderNumber': typeof OrdersOrderNumberRoute
  '/product/$slug': typeof ProductSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/women/$subcategory': typeof WomenSubcategoryRoute
  '/accessories/': typeof AccessoriesIndexRoute
  '/account/': typeof AccountIndexRoute
  '/men/': typeof MenIndexRoute
  '/women/': typeof WomenIndexRoute
  '/account/orders/$orderNumber': typeof AccountOrdersOrderNumberRoute
  '/api/account/orders': typeof ApiAccountOrdersRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bridal': typeof BridalRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/privacy': typeof PrivacyRoute
  '/ready-to-wear': typeof ReadyToWearRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/returns': typeof ReturnsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sale': typeof SaleRoute
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/unstitched': typeof UnstitchedRoute
  '/wishlist': typeof WishlistRoute
  '/accessories/$subcategory': typeof AccessoriesSubcategoryRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/api/newsletter': typeof ApiNewsletterRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/product': typeof ApiProductRoute
  '/api/search': typeof ApiSearchRoute
  '/api/track-order': typeof ApiTrackOrderRoute
  '/api/wishlist-entries': typeof ApiWishlistEntriesRoute
  '/category/$slug': typeof CategorySlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/men/$subcategory': typeof MenSubcategoryRoute
  '/orders/$orderNumber': typeof OrdersOrderNumberRoute
  '/product/$slug': typeof ProductSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/women/$subcategory': typeof WomenSubcategoryRoute
  '/accessories': typeof AccessoriesIndexRoute
  '/account': typeof AccountIndexRoute
  '/men': typeof MenIndexRoute
  '/women': typeof WomenIndexRoute
  '/account/orders/$orderNumber': typeof AccountOrdersOrderNumberRoute
  '/api/account/orders': typeof ApiAccountOrdersRoute
  '/account/orders': typeof AccountOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/bridal': typeof BridalRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/privacy': typeof PrivacyRoute
  '/ready-to-wear': typeof ReadyToWearRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/returns': typeof ReturnsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sale': typeof SaleRoute
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/unstitched': typeof UnstitchedRoute
  '/wishlist': typeof WishlistRoute
  '/accessories/$subcategory': typeof AccessoriesSubcategoryRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/api/newsletter': typeof ApiNewsletterRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/product': typeof ApiProductRoute
  '/api/search': typeof ApiSearchRoute
  '/api/track-order': typeof ApiTrackOrderRoute
  '/api/wishlist-entries': typeof ApiWishlistEntriesRoute
  '/category/$slug': typeof CategorySlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/men/$subcategory': typeof MenSubcategoryRoute
  '/orders/$orderNumber': typeof OrdersOrderNumberRoute
  '/product/$slug': typeof ProductSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/women/$subcategory': typeof WomenSubcategoryRoute
  '/accessories/': typeof AccessoriesIndexRoute
  '/account/': typeof AccountIndexRoute
  '/men/': typeof MenIndexRoute
  '/women/': typeof WomenIndexRoute
  '/account/orders/$orderNumber': typeof AccountOrdersOrderNumberRoute
  '/api/account/orders': typeof ApiAccountOrdersRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/bridal'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faqs'
    | '/forgot-password'
    | '/login'
    | '/new-arrivals'
    | '/privacy'
    | '/ready-to-wear'
    | '/refund-policy'
    | '/register'
    | '/reset-password'
    | '/returns'
    | '/robots.txt'
    | '/sale'
    | '/search'
    | '/shipping'
    | '/sitemap.xml'
    | '/terms'
    | '/track-order'
    | '/unstitched'
    | '/wishlist'
    | '/accessories/$subcategory'
    | '/account/addresses'
    | '/api/newsletter'
    | '/api/orders'
    | '/api/product'
    | '/api/search'
    | '/api/track-order'
    | '/api/wishlist-entries'
    | '/category/$slug'
    | '/collections/$slug'
    | '/men/$subcategory'
    | '/orders/$orderNumber'
    | '/product/$slug'
    | '/products/$slug'
    | '/women/$subcategory'
    | '/accessories/'
    | '/account/'
    | '/men/'
    | '/women/'
    | '/account/orders/$orderNumber'
    | '/api/account/orders'
    | '/account/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bridal'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faqs'
    | '/forgot-password'
    | '/login'
    | '/new-arrivals'
    | '/privacy'
    | '/ready-to-wear'
    | '/refund-policy'
    | '/register'
    | '/reset-password'
    | '/returns'
    | '/robots.txt'
    | '/sale'
    | '/search'
    | '/shipping'
    | '/sitemap.xml'
    | '/terms'
    | '/track-order'
    | '/unstitched'
    | '/wishlist'
    | '/accessories/$subcategory'
    | '/account/addresses'
    | '/api/newsletter'
    | '/api/orders'
    | '/api/product'
    | '/api/search'
    | '/api/track-order'
    | '/api/wishlist-entries'
    | '/category/$slug'
    | '/collections/$slug'
    | '/men/$subcategory'
    | '/orders/$orderNumber'
    | '/product/$slug'
    | '/products/$slug'
    | '/women/$subcategory'
    | '/accessories'
    | '/account'
    | '/men'
    | '/women'
    | '/account/orders/$orderNumber'
    | '/api/account/orders'
    | '/account/orders'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/bridal'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faqs'
    | '/forgot-password'
    | '/login'
    | '/new-arrivals'
    | '/privacy'
    | '/ready-to-wear'
    | '/refund-policy'
    | '/register'
    | '/reset-password'
    | '/returns'
    | '/robots.txt'
    | '/sale'
    | '/search'
    | '/shipping'
    | '/sitemap.xml'
    | '/terms'
    | '/track-order'
    | '/unstitched'
    | '/wishlist'
    | '/accessories/$subcategory'
    | '/account/addresses'
    | '/api/newsletter'
    | '/api/orders'
    | '/api/product'
    | '/api/search'
    | '/api/track-order'
    | '/api/wishlist-entries'
    | '/category/$slug'
    | '/collections/$slug'
    | '/men/$subcategory'
    | '/orders/$orderNumber'
    | '/product/$slug'
    | '/products/$slug'
    | '/women/$subcategory'
    | '/accessories/'
    | '/account/'
    | '/men/'
    | '/women/'
    | '/account/orders/$orderNumber'
    | '/api/account/orders'
    | '/account/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  BridalRoute: typeof BridalRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  FaqsRoute: typeof FaqsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  NewArrivalsRoute: typeof NewArrivalsRoute
  PrivacyRoute: typeof PrivacyRoute
  ReadyToWearRoute: typeof ReadyToWearRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReturnsRoute: typeof ReturnsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SaleRoute: typeof SaleRoute
  SearchRoute: typeof SearchRoute
  ShippingRoute: typeof ShippingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TrackOrderRoute: typeof TrackOrderRoute
  UnstitchedRoute: typeof UnstitchedRoute
  WishlistRoute: typeof WishlistRoute
  AccessoriesSubcategoryRoute: typeof AccessoriesSubcategoryRoute
  ApiNewsletterRoute: typeof ApiNewsletterRoute
  ApiOrdersRoute: typeof ApiOrdersRoute
  ApiProductRoute: typeof ApiProductRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiTrackOrderRoute: typeof ApiTrackOrderRoute
  ApiWishlistEntriesRoute: typeof ApiWishlistEntriesRoute
  CategorySlugRoute: typeof CategorySlugRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  MenSubcategoryRoute: typeof MenSubcategoryRoute
  OrdersOrderNumberRoute: typeof OrdersOrderNumberRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  WomenSubcategoryRoute: typeof WomenSubcategoryRoute
  AccessoriesIndexRoute: typeof AccessoriesIndexRoute
  MenIndexRoute: typeof MenIndexRoute
  WomenIndexRoute: typeof WomenIndexRoute
  ApiAccountOrdersRoute: typeof ApiAccountOrdersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridal': {
      id: '/bridal'
      path: '/bridal'
      fullPath: '/bridal'
      preLoaderRoute: typeof BridalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-arrivals': {
      id: '/new-arrivals'
      path: '/new-arrivals'
      fullPath: '/new-arrivals'
      preLoaderRoute: typeof NewArrivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ready-to-wear': {
      id: '/ready-to-wear'
      path: '/ready-to-wear'
      fullPath: '/ready-to-wear'
      preLoaderRoute: typeof ReadyToWearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale': {
      id: '/sale'
      path: '/sale'
      fullPath: '/sale'
      preLoaderRoute: typeof SaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unstitched': {
      id: '/unstitched'
      path: '/unstitched'
      fullPath: '/unstitched'
      preLoaderRoute: typeof UnstitchedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories/': {
      id: '/accessories/'
      path: '/accessories'
      fullPath: '/accessories/'
      preLoaderRoute: typeof AccessoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories/$subcategory': {
      id: '/accessories/$subcategory'
      path: '/accessories/$subcategory'
      fullPath: '/accessories/$subcategory'
      preLoaderRoute: typeof AccessoriesSubcategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/api/newsletter': {
      id: '/api/newsletter'
      path: '/api/newsletter'
      fullPath: '/api/newsletter'
      preLoaderRoute: typeof ApiNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders': {
      id: '/api/orders'
      path: '/api/orders'
      fullPath: '/api/orders'
      preLoaderRoute: typeof ApiOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/product': {
      id: '/api/product'
      path: '/api/product'
      fullPath: '/api/product'
      preLoaderRoute: typeof ApiProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track-order': {
      id: '/api/track-order'
      path: '/api/track-order'
      fullPath: '/api/track-order'
      preLoaderRoute: typeof ApiTrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wishlist-entries': {
      id: '/api/wishlist-entries'
      path: '/api/wishlist-entries'
      fullPath: '/api/wishlist-entries'
      preLoaderRoute: typeof ApiWishlistEntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/men/': {
      id: '/men/'
      path: '/men'
      fullPath: '/men/'
      preLoaderRoute: typeof MenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/men/$subcategory': {
      id: '/men/$subcategory'
      path: '/men/$subcategory'
      fullPath: '/men/$subcategory'
      preLoaderRoute: typeof MenSubcategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderNumber': {
      id: '/orders/$orderNumber'
      path: '/orders/$orderNumber'
      fullPath: '/orders/$orderNumber'
      preLoaderRoute: typeof OrdersOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/women/': {
      id: '/women/'
      path: '/women'
      fullPath: '/women/'
      preLoaderRoute: typeof WomenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/women/$subcategory': {
      id: '/women/$subcategory'
      path: '/women/$subcategory'
      fullPath: '/women/$subcategory'
      preLoaderRoute: typeof WomenSubcategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders/': {
      id: '/account/orders/'
      path: '/orders'
      fullPath: '/account/orders/'
      preLoaderRoute: typeof AccountOrdersIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders/$orderNumber': {
      id: '/account/orders/$orderNumber'
      path: '/orders/$orderNumber'
      fullPath: '/account/orders/$orderNumber'
      preLoaderRoute: typeof AccountOrdersOrderNumberRouteImport
      parentRoute: typeof AccountRoute
    }
    '/api/account/orders': {
      id: '/api/account/orders'
      path: '/api/account/orders'
      fullPath: '/api/account/orders'
      preLoaderRoute: typeof ApiAccountOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteChildren {
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AccountOrdersOrderNumberRoute: typeof AccountOrdersOrderNumberRoute
  AccountOrdersIndexRoute: typeof AccountOrdersIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAddressesRoute: AccountAddressesRoute,
  AccountIndexRoute: AccountIndexRoute,
  AccountOrdersOrderNumberRoute: AccountOrdersOrderNumberRoute,
  AccountOrdersIndexRoute: AccountOrdersIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  BridalRoute: BridalRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  FaqsRoute: FaqsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  NewArrivalsRoute: NewArrivalsRoute,
  PrivacyRoute: PrivacyRoute,
  ReadyToWearRoute: ReadyToWearRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReturnsRoute: ReturnsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SaleRoute: SaleRoute,
  SearchRoute: SearchRoute,
  ShippingRoute: ShippingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TrackOrderRoute: TrackOrderRoute,
  UnstitchedRoute: UnstitchedRoute,
  WishlistRoute: WishlistRoute,
  AccessoriesSubcategoryRoute: AccessoriesSubcategoryRoute,
  ApiNewsletterRoute: ApiNewsletterRoute,
  ApiOrdersRoute: ApiOrdersRoute,
  ApiProductRoute: ApiProductRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiTrackOrderRoute: ApiTrackOrderRoute,
  ApiWishlistEntriesRoute: ApiWishlistEntriesRoute,
  CategorySlugRoute: CategorySlugRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  MenSubcategoryRoute: MenSubcategoryRoute,
  OrdersOrderNumberRoute: OrdersOrderNumberRoute,
  ProductSlugRoute: ProductSlugRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  WomenSubcategoryRoute: WomenSubcategoryRoute,
  AccessoriesIndexRoute: AccessoriesIndexRoute,
  MenIndexRoute: MenIndexRoute,
  WomenIndexRoute: WomenIndexRoute,
  ApiAccountOrdersRoute: ApiAccountOrdersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
