-- Phase 8 item 5 — Supabase Auth, account pages, wishlist merge.
--
-- Two things Section 8.3 does not provide, both recorded here as deliberate
-- ADDITIONS in the same style as `orders.ship_notes` in 0001:
--
--   1. An `addresses` table. Section 11.6 lists "addresses" as an account page,
--      but 8.3 stores an address only as the ship_* columns on an order. Those
--      are a historical record of where one parcel went, not a book the
--      customer can edit, so a page built on them could only ever be read-only.
--
--   2. A source of order numbers. 8.3 declares `order_number text unique not
--      null` and says nothing about who generates it. Phase 7's in-memory
--      repository used a module counter, which is a race the moment there are
--      two server processes. A Postgres sequence is the only place this can be
--      decided once.

/* ------------------------------------------------------------------ */
/* Order numbers — Section 16 format, generated by the database        */
/* ------------------------------------------------------------------ */

create sequence if not exists order_number_seq;

-- Matches formatOrderNumber() in src/lib/format.ts exactly: KC-2026-00042.
-- Generating it here rather than in the application means two concurrent
-- checkouts cannot be handed the same number, whatever the isolate count.
create or replace function next_order_number() returns text
  language sql
  volatile
as $$
  select 'KC-' || to_char(now(), 'YYYY') || '-' ||
         lpad(nextval('order_number_seq')::text, 5, '0');
$$;

alter table orders alter column order_number set default next_order_number();

/* ------------------------------------------------------------------ */
/* Addresses                                                           */
/* ------------------------------------------------------------------ */

create table if not exists addresses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  label text,
  name text not null,
  phone text not null,
  line1 text not null,
  line2 text,
  city text not null,
  province text not null,
  postal_code text,
  is_default boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists addresses_user_idx on addresses (user_id);

-- At most one default per customer. A partial unique index says that once,
-- rather than every write having to remember to clear the others.
create unique index if not exists addresses_one_default_per_user
  on addresses (user_id)
  where is_default;

alter table addresses enable row level security;

-- Addresses are edited from the browser under the customer's own session, so
-- unlike the catalogue they need write policies. Every one of them is the same
-- clause: the row must belong to the caller.
create policy "customers read their own addresses"
  on addresses for select
  to authenticated
  using (auth.uid() = user_id);

create policy "customers add their own addresses"
  on addresses for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "customers edit their own addresses"
  on addresses for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "customers delete their own addresses"
  on addresses for delete
  to authenticated
  using (auth.uid() = user_id);
